version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.development      

    environment:
      - "DB_HOST=postgres"

    volumes:
      - "./website/app:/var/www/app"
      - "./website/storage:/var/www/storage"
      - "./website/resources:/var/www/resources"
      - "./website/routes:/var/www/routes"

    ports:
      - "8000:8000"
      - "35729:35729"

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: pg!password
    ports:
      - "4321:80"
    depends_on:
      - postgres
