CREATE schema IF NOT EXISTS lbaw2264;
SET search_path TO lbaw2264;

INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-07-27 11:28:33', 'twilkinson@example.com', '$2y$10$bPDr09knNvuexsf.lENW7..iGq6/C76FLEDk2HvRWlS8vOQ3ShNbe', 'twilkinson', 'Jada', 'Schneider', 'Software engineer @ Deloitte', NULL, 'https://north-live.s3.eu-west-2.amazonaws.com/wp-content/uploads/2019/08/13163254/Dean-Costello-19-180px-x-180px.jpg', 'https://wonderfulengineering.com/wp-content/uploads/2014/09/Purple-wallpaper-7-150x60.jpg', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-07-13 21:09:03', 'sarina.kuvalis@example.com', '$2y$10$2AUukoDzA3dnkeG0F3Cepen/jsaMtUUbxu74syTzMdPnkGfdG/FMm', 'sarina.kuvalis', 'Maymie', 'Aufderhar', 'Standing with Ukraine', NULL, 'https://i.cricketcb.com/stats/img/faceImages/1413.jpg', 'https://wonderfulengineering.com/wp-content/uploads/2014/09/Purple-wallpaper-20-150x84.jpg', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2022-07-18 09:48:33', 'ron89@example.com', '$2y$10$0C5FQaQVWAwQIbtIGiqLEeLK1HLcB4t0PEsfBFoaY/LjMGKTO95ae', 'ron89', 'Aiyana', 'Stanton', 'I''m here for the cat news', NULL, 'https://avatarfiles.alphacoders.com/132/132594.jpg', 'https://ijunkie.com/wp-content/uploads/2015/10/iphone-6s-live-wallpaper-5-194x129.png', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-01-22 03:57:30', 'pearl.stark@example.com', '$2y$10$.FI8nszeb65DQ8BQvD/ZiOs8KyqyY0WmJaMuhRQrmCXVf8DGQl.ge', 'pearl.stark', 'Laurence', 'Simonis', NULL, NULL, NULL, 'https://www.publicdomainpictures.net/pictures/160000/t2/abstract-wallpaper-1458764328MfN.jpg', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-06-14 18:28:02', 'marco.schmidt@example.com', '$2y$10$DeYNH3aJCtvKLBeDh6LsOuyhvkc/QEPWxr5xpffJeTsboEA7D1JbK', 'marco.schmidt', 'Chad', 'Runolfsdottir', 'Só sei que nada sei', NULL, 'https://s3-eu-west-2.amazonaws.com/north-live/wp-content/uploads/2019/08/12111103/Ian-Duthrie-12-180px-x-180px.jpg', 'https://images.freeimages.com/images/thumbs/01a/technology-background-1632715.jpg', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-06-01 14:15:10', 'crooks.carmine@example.com', '$2y$10$tlXhnDm0TAEzf1EzGRPTq.BQOY1zPksEdD90XXc3hcCZ4cVYTKFea', 'crooks.carmine', 'Madisyn', 'Feil', 'Love my cats <3', NULL, 'https://images.statusfacebook.com/profile_pictures/blue/blue_profile_pic_09.jpg', NULL, false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2022-02-20 21:34:42', 'bmitchell@example.com', '$2y$10$Zfih0QpzgiY9tTztrP7jx.M4Ffgnl8k2Y1axw40LRmBqOwEBPF4vW', 'bmitchell', 'Verla', 'Jacobs', 'Software engineer @ Continental', NULL, 'https://www.abdn.ac.uk/img/150/staffpages/uploads/s02df9/David_Fisher_McMaster_headshot2.jpg', 'https://download.cnet.com/a/img/resize/185576590eb882c0f3a4dcba1a3ac8a0be543a14/catalog/2020/09/29/6015bc33-7fb2-45ce-a6ef-212e416ac72c/imgingest-9063385355549091545.png?auto=webp&fit=crop&height=675&width=1200', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-10-04 04:59:40', 'tsmitham@example.com', '$2y$10$ySJOaKlX3.p88k47kZfqy.ywCbaOh0XzZeGDJdUrjrDV5mwyA5Swq', 'tsmitham', 'Blair', 'Keebler', 'Student @ FEUP', NULL, 'https://walldiskpaper.com/wp-content/uploads/2015/01/Hamster-Pink-Wallpaper-Photos--150x150.jpg', 'http://christmasstockimages.com/free/Stars/thumbs/paper_star_background.jpg', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-08-14 02:25:00', 'lonnie.oberbrunner@example.com', '$2y$10$Cj8bIBKSOEUbT8ZjiyfnDuH/0lk1YdxXmvstSHy61ViCg8D2cuaBi', 'lonnie.oberbrunner', 'Waylon', 'Lebsack', 'I can''t seem to finish my Bachelor''s...', NULL, NULL, 'https://img.glyphs.co/img?src=aHR0cHM6Ly9zMy5tZWRpYWxvb3QuY29tL3Jlc291cmNlcy9BYnN0cmFjdF9Nb3NhaWNfQmFja2dyb3VuZHNfODAweDUxOC0xLmpwZw&q=85&enlarge=true&h=116&w=178', false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2022-03-26 12:30:08', 'mertz.aric@example.com', '$2y$10$j0eIZt8efkgtyiWsHoHMeOENDxz3Kg7BFnEcgUDQyeB7xbb.mV4q.', 'mertz.aric', 'Holden', 'Waters', 'Possum gang', NULL, 'https://smi-live.s3.eu-west-2.amazonaws.com/wp-content/uploads/2020/06/05132716/Anna-Athanasiadis-180px-x-180px.jpg', 'https://images.pexels.com/photos/169789/pexels-photo-169789.jpeg?h=130&auto=compress&cs=tinysrgb', true, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-08-24 17:13:59', 'dimitri80@example.com', '$2y$10$jugdAk4IYFcNaI4vk0u5kOYRnhrgc5N6orL/SADVyTthjcBImSZtG', 'dimitri80', 'Rico', 'Willms', 'Frogs ftw <3', NULL, 'https://sguru.org/wp-content/uploads/2017/06/steam-avatar-profile-picture-1631.png', 'https://thumbs.dreamstime.com/t/lavender-background-light-purple-48448706.jpg', true, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-12-28 01:21:00', 'sally72@example.com', '$2y$10$XQHt.1wXR0KlfvJqqRr6vOoo53HBXayiM.tHLULYwmPF79hBcyFSa', 'sally72', 'Burnice', 'Steuber', 'Standing with Ukraine', NULL, 'https://www.discordavatars.com/wp-content/uploads/2020/05/125817558761865216.jpg', 'https://download.cnet.com/a/img/resize/808ab8700abdb7c60ffaf6058ae4a56aea3e9e02/catalog/2020/05/18/6caec5f0-174f-4c09-9c5f-8a2163840584/imgingest-5382045460835104770.jpg?auto=webp&fit=crop&height=675&width=1200', true, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2022-05-19 21:17:44', 'travis.von@example.com', '$2y$10$znIZjK3aSEtdyCGzRY25MeDnRYHpC25yxS7SKeJuWGw3/na.Xyo2m', 'travis.von', 'Ezekiel', 'Lynch', 'Marketing! DM me for a promotion',  NULL, NULL, NULL, false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2022-06-07 06:27:09', 'erik10@example.com', '$2y$10$0oRU/CEJOQzSsTbBZ0VB6Oe5Bqt8N9oJu5LkgsXyjHnrOoUNjkv/a', 'erik10', 'Cary', 'Schmeler', NULL, NULL, 'http://ixicreations.weebly.com/uploads/2/6/5/4/26540271/1426201_orig.jpg', NULL, false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-09-10 13:52:30', 'kariane.morissette@example.com', '$2y$10$Yn3Uf..f2OK2STN4/r5.vOSjr5Fi46d0JnqRpX8UxGENe0ovZJufu', 'kariane.morissette', 'Hubert', 'Lang', 'idk what to say here', NULL, 'https://www.cranleighmagazine.co.uk/wp-content/uploads/2017/03/nick-150x180.jpg', NULL, false, NULL);
INSERT INTO Users (created_at, email, password, username, first_name, last_name, bio, block_reason, profile_picture, banner_picture, is_admin, remember_token) VALUES ('2021-12-28 01:21:00', 'crona.sigmund@example.com', '$2y$10$dVfP1rPyv9PWuAlFIL.G4eyPo8nFf.TEYLLB74C7CYyNsGhdfZzU6', 'crona.sigmund', 'Elmer', 'Dietrich', 'I''m the main character', NULL, 'https://attractivepartners.co.uk/wp-content/uploads/2017/06/profile.jpg', 'https://fg-a.com/facebook-images/4th-july-abstract-flag-design-2018-th.jpg', true, NULL);

INSERT INTO Forums (created_at, name, description, forum_picture, banner_picture, hidden) VALUES ('2021-01-01 09:30:41', 'Animals', 'Things that make you go AWW! Like puppies, bunnies, babies, and so on... A place for really cute pictures and videos!', 'https://styles.redditmedia.com/t5_2qh1o/styles/communityIcon_6fzlk8ukx6s51.jpg', 'https://styles.redditmedia.com/t5_2qh1o/styles/bannerBackgroundImage_wmbf6g1dei301.png', false);
INSERT INTO Forums (created_at, name, description, forum_picture, banner_picture, hidden) VALUES ('2020-11-05 10:32:51', 'Portugal', 'Um lugar para discutir Portugal ou portugueses pelo mundo. — A place to debate Portugal and portuguese people around the world.', 'https://styles.redditmedia.com/t5_2qh1o/styles/communityIcon_6fzlk8ukx6s51.jpg', 'https://styles.redditmedia.com/t5_2qmie/styles/bannerBackgroundImage_fp68a8rhz7w81.jpg', false);
INSERT INTO Forums (created_at, name, description, forum_picture, banner_picture, hidden) VALUES ('2022-05-06 05:12:21', 'Politics', 'For news and discussion about U.S. politics', 'https://styles.redditmedia.com/t5_2cneq/styles/communityIcon_fy84mdgh75201.jpg', 'https://styles.redditmedia.com/t5_2cneq/styles/bannerBackgroundImage_4vvj1k5ldn671.png', false);

INSERT INTO ForumOwners (forum_id, owner_id) VALUES (1,5);
INSERT INTO ForumOwners (forum_id, owner_id) VALUES (2,10);
INSERT INTO ForumOwners (forum_id, owner_id) VALUES (3,5);

INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-07-23 10:45:48', '2022-08-15 06:55:54', 'I love my cats', 'I just wanted to share how much I love my cats, I don''t know, they''re so cute. They just like purr purr meow purr I wish I was a cat', 0, 6, 1, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2021-01-03 07:00:39', '2021-10-22 03:48:34', 'Alerta vermelho em Lisboa: Proteção Civil pede à população que fique em casa. Há várias estradas cortadas', 'Cuidado com as cheias, proteção civil pede alerta e atenção com o caos em Lisboa. Podem ler mais aqui: https://sicnoticias.pt/meteorologia/2022-12-13-Distrito-de-Lisboa-em-aviso-vermelho--veja-aqui-as-estradas-cortadas--66bc53d5', 0, 1, 2, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2021-01-22 11:11:46', '2022-08-23 18:10:25', 'Está bonito...', 'Lisboa no dia 12 de dezembro, cuidado', 0, 10, 2, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-09-09 19:02:48', '2022-11-01 19:35:10', 'Portugueses enraivessem-se pouco', 'Mantêmo-nos fortes', 0, 10, 2, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-09-12 19:03:48', '2022-11-25 09:38:10', 'Mashup bandeiras portuguesa e espanhola', 'Achei engraçado', 0, 8, 2, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-09-29 19:03:48', '2022-09-29 19:03:48', 'First thing I see when I get home!', 'He makes me so happy', 0, 4, 1, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-09-29 19:10:48', '2022-09-29 19:10:48', 'a solid sleeper', 'snoozing like a pro', 0, 3, 1, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-11-23 12:53:40', '2022-11-23 12:53:40', 'Funny pictures of my sphynx cat', 'goofy cat', 0, 2, 1, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-10-24 12:53:40', '2022-10-24 12:53:40', 'His face while I''m eating meat', 'Poor thing but I can''t give him any more', 0, 9, 1, false);
INSERT INTO Posts (created_at, last_edited, title, body, rating, owner_id, forum_id, hidden) VALUES ('2022-04-24 12:53:40', '2022-04-24 12:53:40', 'He had a rough day', 'I love watching him sleep. Not in a creepy way!', 0, 7, 1, false);

INSERT INTO PostImages (path, caption, post_id) VALUES ('https://external-preview.redd.it/WRHc5r0gnlGJx1s4fCT4yruOCL6XH8pz-iBMfpPjQi8.jpg?auto=webp&s=4e286d08762212dbfa8fcfe22e91e68ca677909f', 'My cute cat!', 6);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.redd.it/jto6t3kyvm5a1.jpg', 'Notícias 12 dezembro de manhã', 3);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.redd.it/ph1z7ls6mm5a1.png', 'Mapa que discrimina raiva sentida, portugueses quase no topo!', 4);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.redd.it/nd8e1xou5g5a1.png', 'Mashup bandeiras da peninsula ibérica', 5);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.redd.it/rrln22720q5a1.jpg', 'My little baby cat', 7);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://3.bp.blogspot.com/--n9CXmRTaq0/Uo-LBNfcfOI/AAAAAAAAGTM/V06SZNSePBc/s1600/Funny+Sphynx+Cat_2.jpg', 'so fat', 8);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.pinimg.com/originals/b2/1b/d5/b21bd544ec6b3a887350685bdb9cbfb5.jpg', 'He hates the blankie', 8);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.redd.it/2fd7nh9wwp5a1.jpg', 'His face while I''m eating meat', 9);
INSERT INTO PostImages (path, caption, post_id) VALUES ('https://i.redd.it/aisvuxwvco5a1.jpg', 'My cat, meatball', 10);

UPDATE Users SET reputation = 0;
UPDATE Posts SET rating = 0;

INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (2, 1, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (2, 3, NULL, 'dislike');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (1, 2, NULL, 'dislike');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (6, 4, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (5, 4, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (3, 4, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (4, 4, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (7, 1, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (7, 2, NULL, 'dislike');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (8, 6, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (10, 1, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (14, 9, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (14, 1, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (14, 2, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (14, 10, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (13, 10, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (13, 9, NULL, 'like');
INSERT INTO Ratings (owner_id, rated_post_id, rated_comment_id, type) VALUES (12, 10, NULL, 'dislike');

INSERT INTO Comments (created_at, last_edited, body, rating, owner_id, post_id, hidden) VALUES ('2022-07-24 23:52:26', '2022-07-24 23:52:26', 'Big same, I feel so much love towards my cat', 0, 1, 1, false);
INSERT INTO Comments (created_at, last_edited, body, rating, owner_id, post_id, hidden) VALUES ('2022-07-25 23:52:26', '2022-07-25 23:52:26', 'Muito cuidado mesmo. Nem vou sair de casa hoje', 0, 3, 3, false);
INSERT INTO Comments (created_at, last_edited, body, rating, owner_id, post_id, hidden) VALUES ('2022-07-26 11:00:26', '2022-07-25 11:00:26', 'Mantenham-se abrigados, não se pode lá fora...', 0, 4, 3, false);
INSERT INTO Comments (created_at, last_edited, body, rating, owner_id, post_id, hidden) VALUES ('2022-07-26 12:52:26', '2022-07-25 23:52:26', 'De facto, o site do IPMA não é tão catastrofista. Está em risco laranja até às 15h e entre as 15h e as 18h em amarelo. A partir das 18h, já está a verde. Considerando que durante a noite e manhã, estava a vermelho, pior do que foi a manhã não há de ser, pelo menos. O problema é mesmo se continuam a haver muitas zonas onda ainda esteja muita água por escoar e muito por limpar e aí é que pode complicar.
E o artigo também diz que o Metro de Lisboa tem o serviço afetado, mas a circulação de comboios está normal (bem, normal com o ocasional atraso, mas isso é mesmo o normal), o que há é acessos condicionados. A última atualização (às 11h40) do Twitter oficial diz que neste momento a única coisa fechada é o átrio de Entre Campos que liga aos comboios. Chelas e Sete Rios estiveram fechados, mas já reabriram e os comboios a circular em todo o lado.
Só para clarificar, não estou a tentar diminuir a importância disto, obviamente que vai ser preciso continuar a ter cuidados durante o dia de hoje. Mas vale a pena tentar consultar sempre as fontes oficiais para informações mais fiáveis e concretas do que confiar no sensacionalismo da comunicação social.', 0, 7, 3, false);
INSERT INTO Comments (created_at, last_edited, body, rating, owner_id, post_id, hidden) VALUES ('2022-07-25 23:52:26', '2022-07-25 23:52:26', 'E hoje que tenho apresentação...', 0, 2, 3, false);

INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (1, 2, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (1, 3, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (1, 4, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (1, 7, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (1, 10, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (4, 2, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (4, 3, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (4, 10, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (5, 10, NULL);
INSERT INTO Follows (owner_id, followed_user_id, followed_forum_id) VALUES (10, 5, NULL);

INSERT INTO Reports(created_at, reason, type, reporter_id, forum_id, post_id, comment_id) VALUES ('2022-07-26 12:52:26', 'This post has explicit content', 'post', 1, NULL, 3, NULL);
INSERT INTO Reports(created_at, reason, type, reporter_id, forum_id, post_id, comment_id) VALUES ('2022-12-26 12:52:26', 'This post showed on my homepage, honestly I don''t like this kind of content, it''s slightly disturbing to me and I''d rather it was moderated. If you don''t delete this, at least add a NSFW tag with a blurry picture', 'post', 6, NULL, 5, NULL);
INSERT INTO Reports(created_at, reason, type, reporter_id, forum_id, post_id, comment_id) VALUES ('2022-12-27 12:52:26', 'This post showed on my homepage, honestly I don''t like this kind of content, it''s slightly disturbing to me and I''d rather it was moderated. If you don''t delete this, at least add a NSFW tag with a blurry picture', 'post', 6, NULL, 5, NULL);
INSERT INTO Reports(created_at, reason, type, reporter_id, forum_id, post_id, comment_id) VALUES ('2022-12-30 12:52:26', 'I''m in this post and I don''t like it', 'post', 7, NULL, 2, NULL);
INSERT INTO Reports(created_at, reason, type, reporter_id, forum_id, post_id, comment_id) VALUES ('2023-01-01 12:52:26', 'This comment made me feel disturbed, please take it down', 'comment', 6, NULL, NULL, 5);