version: "3"
services:
  website:
    container_name: website
    restart: always
    build: ./website
    depends_on: 
      - postgres 
    ports:
      - "8000:8000"
      
  nginx:
    image: nginx:stable
    restart: always
    ports: 
      - "80:80"
    depends_on: 
      - website

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    volumes: 
      - .data/postgres:/var/lib/postgresql/data  
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@lbaw
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "4321:80"
    depends_on:
      - postgres
  
